# language: node_js

services:
  - docker

# before_install:
#   - docker pull node:9

install:
  - docker build -t dbs-scraper .

script:
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - mkdir ${TRAVIS_BUILD_DIR}/release
  - docker run -v ${TRAVIS_BUILD_DIR}/release:/home/node/app/release dbs-scraper cp ./src/cards.json /home/node/app/release/cards.json
  - docker run --rm -v ${TRAVIS_BUILD_DIR}/build:/home/node/app/web-page/build dbs-scraper yarn build

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: release/cards.json
    skip_cleanup: true
    on:
      tags: false
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_OAUTH_TOKEN
    keep-history: false
    local-dir: build/
    varbose: true
    on:
      branches:
        only:
          - gh-pages
      