name: 'DBS Scraper | Update'

# on:
#   schedule:
#     - cron:  '0 6 * * *'
on: push

jobs:

  get_cards:
    name: 'Scrap page & get cards'
    runs-on: ubuntu-latest
    env:
      NEW_CARDS: false
      LATEST_RELEASE_CARDS_FILE: ./cards-latest_release.json
      TODAY_CARDS_FILE: ./cards.json

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download cards.json from latest release
        uses: Xotl/cool-github-releases@v1
        with:
          assets: cards.json|${{env.LATEST_RELEASE_CARDS_FILE}}
          github_token: ${{ github.token }} 

      - name: Scrap page for cards.json
        env: 
          CARDS_OUTPUT: ${{env.TODAY_CARDS_FILE}}
        run: |
          docker build -t dbs-scraper ./scraper
          chmod +x tools/get-cards-file.sh
          ./tools/get-cards-file.sh
          ls

      - name: Check if there are differences
        run: |
          if [ "$(cat ${{env.LATEST_RELEASE_CARDS_FILE}})" != "$(cat ${{env.TODAY_CARDS_FILE}})" ]; \
          then echo ::set-env name=NEW_CARDS::true; fi

      - name: Create new release
        if: env.NEW_CARDS == true
        run: echo "Needs to create a new release"